### ISSUE TITLE
Enforce minimum box size

### ISSUE THREAD

**Issue by antingshen** [antingshen/BeaverDam#4]
Create a global config parameter `min_size`, such that if the user tries to create any box's width or height is smaller that `min_size`, ignore it and do nothing.

**Comment by allenywang** [comment]
Should it be a global config parameter or a class variable?

**Comment by antingshen** [comment]
Either works

**Comment by antingshen** [comment]
Where is this parameter btw? @szhu

**Comment by szhu** [comment]
Oh yes. Fixed by df5f8a35f2dd9fd05858335230d6dd0597900e4f initially.

EDIT: IGNORE BELOW, IT'S WRONG. [THIS IS CORRECT](#issuecomment-235753669)

~~23f09b40f2b94c2f8c6aa079e1d0c394992b0f02 introduced a second variable, `RESIZE_BORDER_CORNER`, to make the corner area larger.~~

~~Parameters are in `Rect.RESIZE_BORDER_EDGE` and `Rect.RESIZE_BORDER_CORNER` in [views/rect.js](https://github.com/antingshen/BeaverDam/blob/2bdfb22f83dfb76838b33f9d270ddaf3949be993/annotator/static/views/rect.js#L8-L9)~~

**Comment by antingshen** [comment]
What do each of these mean? If I want boxes to be at least some width or height or area, what do I do?

**Comment by szhu** [comment]
Just a note, the way that constants are done now, these variables can be accessed using:
- `Rect.RESIZE_BORDER_CORNER`
- `(any subclass of Rect).RESIZE_BORDER_CORNER` e.g. `CreationRect.RESIZE_BORDER_CORNER`
- `(any Rect object).RESIZE_BORDER_CORNER`
- `RectConstants.RESIZE_BORDER_CORNER` but don't do it this way

**Comment by szhu** [comment]
oh wait j k I looked up the wrong variable.

I meant `Rect.MIN_RECT_DIMENSIONS` in [views/rect.js](https://github.com/antingshen/BeaverDam/blob/2bdfb22f83dfb76838b33f9d270ddaf3949be993/annotator/static/views/rect.js#L11-L15), which was introduced in df5f8a35f2dd9fd05858335230d6dd0597900e4f.

**Comment by antingshen** [comment]
Awesome, thanks
